version: "3.9"
services:
  meilisearch:
    image: "getmeili/meilisearch:v1.7"
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=masterKey